include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/generated_*"
    - "lib/generated/**"
    - "lib/config/l10n/generated/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maintainability-index: 50
    maximum-nesting: 5
    number-of-parameters: 5
    source-lines-of-code: 80
    technical-debt:
      threshold: 16
      todo-cost: 4
      ignore-cost: 8
      ignore-for-file-cost: 16
      as-dynamic-cost: 16
      deprecated-annotations-cost: 2
      file-nullsafety-migration-cost: 2
      unit-type: "hours"
  metrics-exclude:
    - test/**
  rules:
    - avoid-throw-in-catch-block
    - prefer-const-border-radius
    - arguments-ordering:
      child-last: true
    - avoid-cascade-after-if-null
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-border-all
    - avoid-shrink-wrap-in-lists
    - avoid-collection-methods-with-unrelated-types:
        strict: false
    - avoid-global-state
    - avoid-missing-enum-constant-in-map
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - binary-expression-operand-order
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-object-declaration
    - prefer-async-await
    - prefer-conditional-expressions
    - prefer-correct-type-name:
        max-length: 44
    - prefer-first
    - prefer-last
    - prefer-trailing-comma
    - always-remove-listener
    - avoid-expanded-as-spacer
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-correct-edge-insets-constructor
    - prefer-define-hero-tag
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - prefer-using-list-view
linter:
  rules:
    one_member_abstracts: false
    public_member_api_docs: false
    type_annotate_public_apis: false
    prefer_mixin: false
    lines_longer_than_80_chars: false
    avoid_classes_with_only_static_members: false
    sort_child_properties_last: true
    use_string_in_part_of_directives: true
    avoid_renaming_method_parameters: false
    library_private_types_in_public_api: false
    annotate_overrides: false
    null_closures: false
    recursive_getters: false
    use_build_context_synchronously: false
    unrelated_type_equality_checks: false
